name: docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      # DOCS_GA_ID: G-
      NODE_VERSION: '18'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@8.9.2 --activate
          pnpm --version
          pnpm install

      - name: Build documentation site
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          repo: chaldea-center/chaldea-center.github.io
          target_branch: main
          build_dir: docs/.vitepress/dist
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}
